name: car_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  getwidget: ^3.1.1
  get: ^4.6.5
  flutter_file_dialog: ^3.0.2
  screenshot: ^3.0.0
  draggable_fab: ^0.1.1
  printing: ^5.13.4
  arabic_font: ^0.0.9
  flutter_localization: ^0.1.13
  cool_alert: ^2.0.1
  cached_network_image: ^3.2.3
  dio: ^5.3.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^4.0.1
  pretty_dio_logger: ^1.3.1
  flashy_tab_bar2: ^0.0.6
  share_plus: ^7.0.2
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  upgrader: ^8.0.0
  in_app_update: ^4.2.2
  shared_preferences: ^2.2.0
  flutter_animate: ^4.2.0
  file_picker: ^5.3.3
  map_launcher: ^3.5.0
  flutter_html: ^3.0.0-alpha.3
  pdf: ^3.10.4
  url_launcher: ^6.1.12
  video_player: ^2.7.2
  local_auth: ^2.1.6
  star_rating: ^0.11.0
  in_app_review: ^2.0.6
  image_picker: ^1.0.1
  easy_localization: ^3.0.2
  pinch_zoom: ^1.0.0
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  flutter_native_splash: ^2.4.0

  intl: ^0.19.0
  bubble: ^1.2.1
  file_icon: ^1.0.0
  flutter_pdfview: 1.3.2
  video_compress: ^3.1.3
  flutter_linkify: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  modal_progress_hud_nsn: ^0.5.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/baby-car.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart
  ignore_comments: true
  classname: AppAssets
  field_prefix: null
